#  Application Properties
spring.application.name=task-queue
server.port=8080

# Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
# spring.data.redis.timeout=6000


# Logging Configuration
logging.level.com.mreyes.task_queue=DEBUG
logging.level.org.springframework.data.redis=DEBUG

# PostgreSQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskqueue}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mreyes}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection pool
spring.datasource.hikari.maximum-pool-size=10

# Actuator endpoints(IBM style)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.redis.enabled=true
management.health.db.enabled=true